services:
  - type: web
    name: udp-latency-analysis
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python web_app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PORT
        value: 10000
    healthCheckPath: / 